
spring:
 jpa:
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
    show_sql: true
    use_sql_comments: true
    format_sql: true
  hibernate:
   ddl-auto: update
 datasource:
  url: jdbc:mysql://fx-mysql:3306/fxmysql
  username: fxmysqluser
  password: fxmysqlpassword