
spring:
 jpa:
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
    show_sql: true
    use_sql_comments: true
    format_sql: true
  hibernate:
   ddl-auto: update
 datasource:
  url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
  username: ${MYSQL_USER}
  password: ${MYSQL_PASSWORD}